services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=user_password
      - DB_NAME=techoazis_db
    networks:
      - techoazis-net

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: techoazis_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./techoazis_db.sql:/docker-entrypoint-initdb.d/01_structure.sql
      - ./techoazis_db_datas.sql:/docker-entrypoint-initdb.d/02_data.sql
    networks:
      - techoazis-net

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root_password
    networks:
      - techoazis-net

networks:
  techoazis-net:
    driver: bridge